### ISSUE TITLE
Invalid example in the readme

### ISSUE THREAD

**Issue by alteralt** [ErVinTract/AioCrypto#1]
![image](https://user-images.githubusercontent.com/109542778/180600421-3d12e4e0-65b7-47a7-9d9c-0f6196ae6787.png)

In readmi, it is
```python3
from AioCrypto import CryptoApi
```

worth replacing it with this
```python3
from aiocryptoimport CryptoApi
```
![image](https://user-images.githubusercontent.com/109542778/180600495-9e7ca3a7-d073-4844-a449-40cd30d56a79.png)

**Comment by ErVinTract** [comment]
> ![image](https://user-images.githubusercontent.com/109542778/180600421-3d12e4e0-65b7-47a7-9d9c-0f6196ae6787.png)
> 
> In readmi, it is
> 
> ```python
> from AioCrypto import CryptoApi
> ```
> 
> worth replacing it with this
> 
> ```python
> from aiocryptoimport CryptoApi
> ```
> 
> ![image](https://user-images.githubusercontent.com/109542778/180600495-9e7ca3a7-d073-4844-a449-40cd30d56a79.png)

Yes, thanks, I forgot about the fact that imported libraries need to be written with a small letter

**Comment by alteralt** [comment]
> > ![image](https://user-images.githubusercontent.com/109542778/180600421-3d12e4e0-65b7-47a7-9d9c-0f6196ae6787.png)
> > In readmi, it is
> > ```python
> > from AioCrypto import CryptoApi
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > worth replacing it with this
> > ```python
> > from aiocryptoimport CryptoApi
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ![image](https://user-images.githubusercontent.com/109542778/180600495-9e7ca3a7-d073-4844-a449-40cd30d56a79.png)
> 
> Yes, thanks, I forgot about the fact that imported libraries need to be written with a small letter

Accept pull requests :)
